main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path("", views.HomePage.as_view(), name="home_page"),
    path("admin_home_page/", views.AdminHomePage.as_view(login_required=True, admin_required=True), name="admin_home_page"),
    path("add_station_page", views.AddStationPage.as_view(login_required=True, admin_required=True), name="add_station_page"),
    path("add_station/<str:name>/<str:location>/<str:desc>", views.AddStation.as_view(login_required=True, admin_required=True), name="add_station"),
    path("add_train_page",views.AddTrainPage.as_view(login_required=True, admin_required=True), name = "add_train_page"),
    path("add_train",views.AddTrain.as_view(login_required=True, admin_required=True), name = "add_train"),
    path("passenger_registration_page", views.PassengerRegistrationPage.as_view(logout_required=True), name="passenger_registration_page"),
    path("passenger_registration", views.PassengerRegistration.as_view(logout_required=True), name="passenger_registration"),
    path("login_page", views.LoginPage.as_view(logout_required=True), name="login_page"),
    path("login", views.Login.as_view(logout_required=True), name="login"),
    path("logout", views.Logout.as_view(login_required=True), name="logout"),
    path("get_schedule/<str:date>/<str:source>/<str:destination>", views.GetSchedule.as_view(), name="get_schedule"),
    path("seat_selection_page/<str:train_id>", views.SeatSelectionPage.as_view(login_required=True), name="seat_selection_page"),
    path("get_seats/<int:train_id>/<int:car_type_id>/<str:number_of_seats>/", views.GetSeats.as_view(login_required=True), name="get_seats"),
    path("seat_purchase/<int:train_id>/<int:car_type_id>/<str:number_of_seats>/", views.SeatPurchase.as_view(login_required=True), name="seat_purchse"),
    path("my_trips_page/", views.MyTripsPage.as_view(login_required=True), name="my_trips_page"),
    path("get_ticket_page/<int:payment_id>/", views.GetTicketPage.as_view(login_required=True), name="get_ticket_page"),
    path("scheduler_page/", views.SchedulerPage.as_view(login_required=True, admin_required=True), name="scheduler_page"),
    path("day_schedule/", views.DaySchedule.as_view(login_required=True, admin_required=True), name="dey_schedule"),
    path("add_schedule_form/", views.AddScheduleFrom.as_view(login_required=True, admin_required=True), name="add_schedule_form"),
    path("delete_day_schedule/<int:id>/", views.DeleteDaySchedule.as_view(login_required=True, admin_required=True), name="delete_day_schedule"),
    path("edit_schedule_page",views.EditSchedulePage.as_view(login_required=True, admin_required=True),name="edit_schedule_page"),
    path("get_schedule_by_date/<str:source>/<str:date>",views.GetScheduleByDate.as_view(login_required=True, admin_required=True),name="get_schedule_by_date"),
    path("delete_train/<int:train_id>",views.DeleteTrainFromSchedule.as_view(login_required=True, admin_required=True),name="delete_train_from_schedule"),
    path("update_train_time/<int:train_id>/<str:time>",views.UpdateScheduleTime.as_view(login_required=True, admin_required=True),name="delete_train_from_schedule"),
    path("week_schedule_controls/", views.WeekScheduleControls.as_view(login_required=True, admin_required=True), name="week_schedule_controls"),
    path("revert_week_day/<int:index>/", views.RevertWeekDay.as_view(login_required=True, admin_required=True), name="revert_week_day"),
    path("get_week_day_schedule/<int:index>/", views.GetWeekDaySchedule.as_view(login_required=True, admin_required=True), name="get_week_day_schedule"),
    path("delete_week_day_schedule/<int:schedule_id>/<int:day_id>/", views.DeleteWeekDaySchedule.as_view(login_required=True, admin_required=True), name="delete_week_day_schedule"),
    path("add_week_day_schedule_form/<int:index>/", views.AddWeekDayScheduleFrom.as_view(login_required=True, admin_required=True), name="add_week_day_schedule_form"),
    path("add_week_day_schedule/<int:index>/", views.AddWeekDaySchedule.as_view(login_required=True, admin_required=True), name="add_week_day_schedule"),
    path("schedule_applier_controls/", views.ScheduleApplierControls.as_view(login_required=True, admin_required=True), name="schedule_applier_controls"),
    path("apply_schedule/", views.ApplySchedule.as_view(login_required=True, admin_required=True), name="apply_schedule")
]


    # path("add_station_page", views.add_station_page, name="add_station_page"),
    # path("add_station", views.add_station, name="add_station"),
    # path("add_train_page",views.add_train_page, name = "add_train_page"),
    # path("add_train",views.add_train, name = "add_train"),

railway_ticketing_system/urls.py
from django.contrib import admin
from django.urls import path, include
from main import urls

urlpatterns = [
    path('', include(urls)),
    path('admin/', admin.site.urls),
]

templates/add_schedule_form.html
<form class="add_schedule" action="{% url 'main:dey_schedule' %}" method="POST">

    {% csrf_token %}

    <h2>Add schedule</h2>

    <div class="form_control_block">

        <div class="form_control">
            {% comment %} <label for="source">Source:</label> {% endcomment %}
            <input id="source" type="text" name="source" value="{{ source }}" hidden>
        </div>

        <div class="form_control">
            <label for="to">Destination:</label>
            <select id="to" name="dest">
                {% for station in stations %}
                    <option value="{{ station.id }}">{{ station.location }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="form_control">
            <label for="dept">Departure:</label>
            <input type="time" id="dept" name="dept" value="{{ current_datetime }}" required>
        </div>    

        <div class="form_control">
            <label for="f_berth">Number of first class berth cars:</label>
            <input type="number" name="fcb" id="f_berth" value="2" min="0" required>
        </div>
        <div class="form_control">
            <label for="f_berth_fare">Fare for first class berth cars:</label>
            <input type="number" name="fcb_fare" id="f_berth_fare" value="1500" min="0" required>
        </div>

        <div class="form_control">
            <label for="f_seat">Number of first class seat cars:</label>
            <input type="number" name="fcs" id="f_seat" value="3" min="0" required>
        </div>

        <div class="form_control">
            <label for="f_seat_fare">Fare for first class seat cars:</label>
            <input type="number" name="fcs_fare" id="f_seat_fare" value="1200" min="0" required>
        </div>

        <div class="form_control">
            <label for="s_chair">Number of shovan chair cars:</label>
            <input type="number" name="sc" id="s_chair" value="4" min="0" required>
        </div>

        <div class="form_control">
            <label for="s_chair_fare">Fare for shovan chair cars:</label>
            <input type="number" name="sc_fare" id="s_chair_fare" value="750" min="0" required>
        </div>

        <div class="form_control">
            <label for="shovan">Number of shovan cars:</label>
            <input type="number" name="s" id="shovan" value="4" min="0" required>
        </div>

        <div class="form_control">
            <label for="shovan_fare">Fare for shovan cars:</label>
            <input type="number" name="s_fare" id="shovan_fare" value="500" min="0" required>
        </div>        
    </div>
  
    <input class="submit_add_schedule" type="submit" value="Add">
</form>

<div class="message_box">
    
</div>  

templates/add_station.html
<div class="add_station">

    <h2>Add new station</h2>

    <div class="form_control_block">
        <div class="form_control">
            <label for="station_name">Name:</label>
            <input type="text" id="station_name" name="station_name" required>
        </div>

        <div class="form_control">
            <label for="station_location">Location:</label>
            <input type="text" id="station_location" name="station_location" required>
        </div>
        <div class="form_control">
            <label for="station_description">Description:</label>
            <textarea name="station_description" id="station_description" cols="30" rows="3"></textarea>
        </div>        
    </div>

    <button class="submit_add_station" type="submit">
        Add
    </button>
</div>

<div class="message_box">

</div>

templates/add_week_day_schedule_form.html
<form class="add_schedule" action="{% url 'main:add_week_day_schedule' index=index %}" method="POST">

    {% csrf_token %}

    <h2>Add schedule</h2>

    <div class="form_control_block">

        <div class="form_control">
            <input id="source" type="text" name="source" value="{{ source }}" hidden>
        </div>

        <div class="form_control">
            <label for="to">Destination:</label>
            <select id="to" name="dest">
                {% for station in stations %}
                    <option value="{{ station.id }}">{{ station.location }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="form_control">
            <label for="dept">Departure:</label>
            <input type="time" id="dept" name="dept" value="{{ current_datetime }}" required>
        </div>    

        <div class="form_control">
            <label for="f_berth">Number of first class berth cars:</label>
            <input type="number" name="fcb" id="f_berth" value="2" min="0" required>
        </div>
        <div class="form_control">
            <label for="f_berth_fare">Fare for first class berth cars:</label>
            <input type="number" name="fcb_fare" id="f_berth_fare" value="1500" min="0" required>
        </div>

        <div class="form_control">
            <label for="f_seat">Number of first class seat cars:</label>
            <input type="number" name="fcs" id="f_seat" value="3" min="0" required>
        </div>

        <div class="form_control">
            <label for="f_seat_fare">Fare for first class seat cars:</label>
            <input type="number" name="fcs_fare" id="f_seat_fare" value="1200" min="0" required>
        </div>

        <div class="form_control">
            <label for="s_chair">Number of shovan chair cars:</label>
            <input type="number" name="sc" id="s_chair" value="4" min="0" required>
        </div>

        <div class="form_control">
            <label for="s_chair_fare">Fare for shovan chair cars:</label>
            <input type="number" name="sc_fare" id="s_chair_fare" value="750" min="0" required>
        </div>

        <div class="form_control">
            <label for="shovan">Number of shovan cars:</label>
            <input type="number" name="s" id="shovan" value="4" min="0" required>
        </div>

        <div class="form_control">
            <label for="shovan_fare">Fare for shovan cars:</label>
            <input type="number" name="s_fare" id="shovan_fare" value="500" min="0" required>
        </div>        
    </div>
  
    <input class="submit_add_schedule" type="submit" value="Add">
</form>

<div class="message_box">
    
</div>  

templates/admin_home_page.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome-pro-5/css/all.css' %}">
        <link rel="stylesheet" href="{% static 'css/admin_home_page.css' %}">
        <title>Railway Ticketing System</title>
    </head>
    <body>
        {% include "widgets/navbar.html" %}
        
        <h1>ADMIN Controls</h1>

        <div class="modal">
            <i class="far fa-times" id='close'></i>
            <div class="modal_content">

            </div>
        </div>

        <div class="admin_controls">
            <a id='add_train' href="{% url 'main:add_train_page' %}">Add Train</a>
            <a id='add_station' href="{% url 'main:add_station_page' %}">Add Station</a>
            <a id='scheduler' href="{% url 'main:scheduler_page' %}">Scheduler</a>
            <a id='edit_schedule_page' href="{% url 'main:edit_schedule_page' %}">Edit Schedule</a>
        </div>

        <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
        <script src="{% static 'js/admin_home_page.js' %}"></script>
    </body>
</html>

templates/edit_schedule_page.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'css/edit_schedule_page.css' %}">
        <title>Railway Ticketing System</title>
    </head>
    <body>
        {% include "widgets/navbar.html" %}
        
        <h1>Edit Schedules</h1>

        <div class="controls">
            <div class="control">
                <label>Station: </label>
                <select id="source">
                    {% for station in stations %}
                        <option value="{{ station.id }}">{{ station.name }}</option>
                    {% endfor %}
                </select>                
            </div>

            <div class="contro">
                <label for="time">Date:</label>
                <input type="date" id="time" value="{{ date }}">                
            </div>
        
            <button id="get_schedule">Get Schedule</button>            
        </div>

        <div id="trains">
        </div>
    
        <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
        <script src="{% static 'js/edit_schedule_page.js' %}"></script>
    </body>
</html>

templates/edit_schedule_table.html
<table cellspacing="0">
    <tr>
        <th>source</th>
        <th>destination</th>
        <th>departure time</th>
        <th>Actions</th>
    </tr>
    {% for train in trains %}
        <tr id="dataOf{{ train.0.id }}">
            <td id="sourceOf{{ train.0.id }}">{{ train.0.source.name }}</td>
            <td id="destinationOf{{ train.0.id }}">{{ train.0.destination.name }}</td>
            <td><input type="time" value="{{ train.1 }}" id="timeOf{{ train.0.id }}"></td>
            <td><button class = "edit_button" id="{{ train.0.id }}">Update Time</button><button class = "delete_button" id="{{ train.0.id }}">Delete</button></td>
        </tr>
    {% endfor %}
</table>

templates/get_ticket_page.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome-pro-5/css/all.css' %}">
        <link rel="stylesheet" href="{% static 'css/get_ticket_page.css' %}">
        <title>Railway Ticketing System</title>
    </head>
    <body>
        {% include "widgets/navbar.html" %}
        
        <h1>
            Ticket
        </h1>
        
        <div class="ticket">
            <div class="passenger">
                <table>
                    <tr>
                        <td>Passenger Name</td>
                        <td>: {{ passenger_name }}</td>
                    </tr>
                    <tr>
                        <td>Payment amount</td>
                        <td>: {{ payment_amount }}</td>
                    </tr>
                    <tr>
                        <td>Seats</td>
                        <td>: {{ seat_string }}</td>
                    </tr>
                </table>
            </div>
        
            <div class="route">
                <div class="dept">
                    <label>
                        Departure:
                    </label>
                    <table>
                        <tr>
                            <td>From</td>
                            <td>: {{ from.location }}</td>
                        </tr>
                        <tr>
                            <td>Date</td>
                            <td>: {{ from.date }}</td>
                        </tr>
                        <tr>
                            <td>Time</td>
                            <td>: {{ from.time }}</td>
                        </tr>
                    </table>
                </div>

                <div class="arrival">
                    <label>
                        Arrival:
                    </label>
                    <table>
                        <tr>
                            <td>To</td>
                            <td>: {{ to.location }}</td>
                        </tr>
                        <tr>
                            <td>Date</td>
                            <td>: {{ to.date }}</td>
                        </tr>
                        <tr>
                            <td>Time</td>
                            <td>: {{ to.time }}</td>
                        </tr>
                    </table>
                </div>                
            </div>
        </div>

        <button class="download">
            <i class="fad fa-download"></i>
        </button>

        <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
        <script src="{% static 'js/get_ticket_page.js' %}"></script>
    </body>
</html>

templates/passenger_registration_page.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'css/passenger_registration_page.css' %}">
        <title>Railway Ticketing System</title>
    </head>
    <body>
        {% include "widgets/navbar.html" %}
        
        <h1>Register as a passenger</h1>

        <form action="{% url 'main:passenger_registration' %}" method="POST">
            {% csrf_token %}

            <div class="form_control_block">
                <div class="form_control">
                    <label for="name">Name:</label>
                    <input id="name" type="text" name="name" required>
                </div>
                <div class="form_control">
                    <label for="nid">NID:</label>
                    <input id="nid" type="text" name="nid" required>
                </div>
            </div>

            <div class="form_control_block">
                <div class="form_control">
                    <label for="username">Username:</label>
                    <input id="username" type="text" name="username" required>
                </div>
                <div class="form_control">
                    <label for="email">Email:</label>
                    <input id="email" type="email" name="email" required>
                </div>
            </div>

            <div class="form_control_block">
                <div class="form_control">
                    <label for="password">Password:</label>
                    <input id="password" type="password" name="password" required>
                </div>
                <div class="form_control">
                    <label for="retype_password">Retype password:</label>
                    <input id="retype_password" type="password" name="retype_password" required>
                </div>
            </div>

            <input class="submit disabled" type="submit" value="Submit" disabled>
        </form>
        
        <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
        <script src="{% static 'js/passenger_registration_page.js' %}"></script>
    </body>
</html>

templates/schedule.html
{% for schedule in schedules %}
    <div class="schedule" id="day_schedule_{{ schedule.id }}">

        {% if week %}
            <button class="day_schedule_delete" delete="{{ schedule.id }}" href="{% url 'main:delete_week_day_schedule' schedule_id=schedule_id day_id=schedule.id %}">
        {% else %}
            <button class="day_schedule_delete" delete="{{ schedule.id }}" href="{% url 'main:delete_day_schedule' id=schedule.id %}">
        {% endif %}
            <i class="fad fa-trash"></i>
        </button>

        <div class="head">
            <div>{{ schedule.source }}<i class="far fa-long-arrow-right"></i>{{ schedule.destination }}</div>
            <div><i class="far fa-clock"></i><span>{{ schedule.time }}</span></div>
        </div>

        <div class="body">

            {% for car in schedule.cars %}
                <div class="car">
                    <div>
                        {{ car.type }}
                    </div>
                    <hr class="vertical">
                    <div>
                        <span>{{ car.number_of_cars }}</span>
                        <hr>
                        <span>{{ car.seats_per_car }}</span>
                    </div>
                    <div class="fare">
                        <i class="fad fa-coins"></i><span>{{ car.fare }}</span>
                    </div>
                </div>
            {% endfor %}

        </div>
    </div> 
{% endfor %}

{% if add_button_required %}
    {% if week %}
        <button class="schedule_add" id="schedule_add_day" href="{% url 'main:add_week_day_schedule_form' index=schedule_id %}">
    {% else %}
        <button class="schedule_add" id="schedule_add_day" href="{% url 'main:add_schedule_form' %}">
    {% endif %}
        <i class="fas fa-plus"></i>
    </button>
{% endif %}


 

templates/schedule_applier_controls.html
<form class="apply_schedule" method="GET" action="{% url 'main:apply_schedule' %}">
    
    <div>
        <label for="from">From:</label>
        <input type="date" id="from" name="from" min="{{ today }}" value="{{ today }}">
    </div>
    <div>
        <label for="to">To:</label>
        <input type="date" id="to" name="to" min="{{ today }}" value="{{ today }}">
    </div>
    <div>
        <input class="submit" type="submit" value="Apply">
    </div>
</form>

<div class="message_box">

</div>

templates/seat_selection_page.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'css/seat_selection_page.css' %}">
        <title>Railway Ticketing System</title>
    </head>
    <body>
        {% include "widgets/navbar.html" %}
        
        <h1>Select your seats</h1>
        
        <div class="seat_criterias">
            <div>
                <label for="car_type">Car type: </label>
                <select name="car_type" id="car_type">
                    <option value="-1" selected>Select</option>
                    {% for car in cars %}
                        <option value="{% url 'main:get_seats' train_id=train_id car_type_id=car.id number_of_seats='-' %}">{{ car.name }} - Fare: {{ car.fare }}</option>
                    {% endfor %}
                </select>
            </div>
            <div>
                <label for="number_of_seats">Number of seats:</label>
                <input id="number_of_seats" type="range" min="1" max="5" name="number_of_seats" value="1">
                <span class="number_of_seats">1</span>
            </div>
            <div class="seats">
                <span>Your seats:</span>
                <span id="seats"></span>
            </div>
            <div class="controls">
                <button class="check">Get Seats</button>
                <button class="purchase">Purchase</button>
            </div>  
        </div>

        <div class="bill_info">
            <span>Total bill: </span>
            <span class="bill"></span>
            <button id="pay" href="#">Pay</button>
        </div>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js" integrity="sha512-qZvrmS2ekKPF2mSznTQsxqPgnpkI4DNTlrdUmTzrDgektczlKNRRhy5X5AAOnx5S09ydFYWWNSfcEqDTTHgtNA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
        <script src="{% static 'js/seat_selection_page.js' %}"></script>
    </body>
</html>

templates/train_schedules.html
<table border="0" cellspacing="0" cellpadding="0">
    <thead>
        <tr>
            <th>From <i class="far fa-long-arrow-right"></i> To</th>
            <th>Time</th>
            <th>Fare range</th>
            <th>Seat Status</th>
            {% if session.user.login_status %}
                <th>View seats</th>
            {% endif %}
        </tr>
    </thead>
    <tbody>
        {% for train in train_schedules %}
            <tr>
                <td>
                    <span>{{ train.source }}</span>
                    <i class="far fa-long-arrow-right"></i>
                    <span>{{ train.destination }}</span>
                </td>
                <td>{{ train.time }}</td>
                <td><span class="fare_from">{{ train.fare_range.min }}</span> BDT - <span class="fare_from">{{ train.fare_range.max }}</span> BDT</td>
                <td>
                    <div class="seat_status {{ train.seat_status }}">
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                    </div>
                </td>
                {% if session.user.login_status %}
                    <td>
                        <a href="{% url 'main:seat_selection_page' train_id=train.train_id %}"><i class="fas fa-eye"></i></a>
                    </td>
                {% endif %}
            </tr>        
        {% endfor %}
    </tbody>
</table>    

templates/week_schedule_controls.html
<div class="week_days">
    <button disabled class="week_day stars" index="0">
        <i class="fas fa-star"></i>
        <i class="fas fa-star"></i>
        <i class="fas fa-star"></i>
    </button>

    {% for week_day in week_days %}
        <button class="week_day {{ week_day.active }}" href="{% url 'main:get_week_day_schedule' index=week_day.index %}" index="{{ week_day.index }}">
            {{ week_day.day }}
        </button>
    {% endfor %}
    
    <button disabled class="week_day stars" index="6">
        <i class="fas fa-star"></i>
        <i class="fas fa-star"></i>
        <i class="fas fa-star"></i>
    </button>
</div>

<div class="day_schedules">
    {% for schedule in today_schedule %}
        <div class="schedule" id="day_schedule_{{ schedule.id }}">

            <button class="day_schedule_delete" delete="{{ schedule.id }}" href="{% url 'main:delete_week_day_schedule' schedule_id=revert day_id=schedule.id %}">
                <i class="fad fa-trash"></i>
            </button>

            <div class="head">
                <div>{{ schedule.source }}<i class="far fa-long-arrow-right"></i>{{ schedule.destination }}</div>
                <div><i class="far fa-clock"></i><span>{{ schedule.time }}</span></div>
            </div>

            <div class="body">

                {% for car in schedule.cars %}
                    <div class="car">
                        <div>
                            {{ car.type }}
                        </div>
                        <hr class="vertical">
                        <div>
                            <span>{{ car.number_of_cars }}</span>
                            <hr>
                            <span>{{ car.seats_per_car }}</span>
                        </div>
                        <div class="fare">
                            <i class="fad fa-coins"></i><span>{{ car.fare }}</span>
                        </div>
                    </div>
                {% endfor %}

            </div>
        </div> 
    {% endfor %}

    <button class="schedule_add" id="schedule_add_day" href="{% url 'main:add_week_day_schedule_form' index=revert %}">
        <i class="fas fa-plus"></i>
    </button>

    <button class="revert" href="{% url 'main:revert_week_day' index=revert %}" revert="{{ revert }}">
        <i class="fas fa-undo"></i>
    </button>
</div>